### ISSUE TITLE
Incompatibility with scala 2.13.1 due to @nowarn annotation

### ISSUE THREAD

**Issue by mtjon** [zio/zio-kafka#187]
zio-kafka uses the `@nowarn` annotation introduced in Scala 2.13.2, this causes incompatibility with Scala 2.13.1. I have not yet tested with Scala 2.12 or 2.11.

It was apparently added in the `0.10.0` release with [this](https://github.com/zio/zio-kafka/commit/56dae11fc1b78a1d2a61f713d50e97a213c1b371) commit by @egast

**Comment by egast** [comment]
It was added to suppress the false positive _unused_ warning of a _T <:< AnyRef_ evidence. The _@nowarn_ annotation could also be replaced by the _@silent_ annotation from the silencer library, but this means that we add the silencer-lib dependency.
It is probably also possible to suppress the warning by adding a silencer expressions in build.sbt, but I'm not sure how maintainable this is.
Since the _nowarn_ annotation is part of the Scala library, it has my preference to use this one.
@mtjon Is there a reason why you are on 2.13.1 and not on 2.13.2? Upgrading should be no problem.

**Comment by mtjon** [comment]
I did upgrade to Scala 2.13.2 when I found out that `@nowarn` was feature introduced in 2.13.2. I also understand your preference of using a feature that's part of the standard Scala library. Certainly over the other options you mentioned.

I did think it was worth making an issue for, as I believe Scala 2.13.x is generally supported across the different ZIO projects. And @svroonland asked me to on Discord. ;) 
If the choice not to support Scala 2.13.1 was made, perhaps this may want to be made explicit in a  note somewhere? I haven't come across any mention of it.

**Comment by svroonland** [comment]
@nowarn was added to scala-collection-compat https://github.com/scala/scala-collection-compat/releases/tag/v2.1.6, which is part of our build.

Shouldn't zio-kafka work with 2.13.1 as well then?

**Comment by svroonland** [comment]
Since the issue is open for a year now, I haven't seen other reports of this and I'm not sure what to do otherwise:

I think with scala-collection-compat 2.1.6 there should be no problem. If not, we're now at scala 2.13.6, so likely most users have upgraded to 2.13.2 or higher. Feel free to re-open if there is still an issue caused by this.
