### ISSUE TITLE
probable concurrency bug using multiple consumers

### ISSUE THREAD

**Issue by TimPigden** [zio/zio-kafka#64]
This can be demonstrated on PR labelled Client Admin

To reproduce, edit in tests zio.kafka.client.EmbeddedMultiConsumerTest
change the test in the list from testMultipleConsumers to testParallelConsumers

On my system it will hang without returning almost all the time but not all the time.
Code for testMultipleConsumers is:
```scala
  val testMultipleConsumers = testM("test multiple consumers") {
    for {
      topic           <- randomTopic
      consumerGroupId <- randomGroup
      _               <- makeTopic(topic, 5)
      _               <- makeMany(topic, 1000)
      _               <- Live.live(ZIO.sleep(2.seconds))
      consumed        = 0.to(4).map(i => MultiConsumerTestHelper.consumeN(topic, consumerGroupId, i, 3))
      _               <- ZIO.collectAll(consumed)
    } yield {
      assertCompletes
    }
  }
```
For testParallelConsumers I simply change collectAll to collectAllPar

**Comment by svroonland** [comment]
The failing test has to do with how Kafka treats multiple consumers in the same consumer group.

When you have multiple active consumers with the same group ID, Kafka will divide the partitions over them. For each consumer that gets added to the group, the partitions are rebalanced. Since you start the consumers in parallel, it is non-deterministic which consumers get which partition and at which time.

In `MultiConsumerTestHelper.consumeN` you filter the stream to include only one expected `TopicPartition`. If you remove the line `.filter(_._1 == tp)` your test succeeds.

**Comment by iravid** [comment]
Thank you for diagnosing @svroonland!

**Comment by TimPigden** [comment]
awesome! I'll update the tests in the PR and resubmit with this in
