### ISSUE TITLE
Add a ZIO Streams-based interface for interacting with the consumer

### ISSUE THREAD

**Issue by iravid** [zio/zio-kafka#8]
For starters, we need an interface that will allow consuming the consumer's data as a `StreamChunk[Throwable, Record[K, V]]`, where `Record` is something like:
```scala
case class Record[K, V](key: K, value: V, timestamp: Long, metadata: Metadata)
case class Metadata(topicPartition: TopicPartition, offset: Long)
```

An important part for achieving good throughput is decoupling the consumption from processing:
- The consumer must be polled in a separate fiber from the rest of the stream with the data transferred to the stream via a bounded queue
- When the queue is full, the partitions on the consumer must be paused and polling must continue (or the consumer will be removed from the consumer group)
- Commits should be fed back to the consumer fiber via another queue and be processed by the polling fiber

See https://github.com/iravid/fs2-kafka-streams/blob/master/src/main/scala/com/iravid/fs2/kafka/client/RecordStream.scala#L262 for a previous implementation.

**Comment by thiloplanz** [comment]
> polling must continue (or the consumer will be removed from the consumer group)

Is this still an issue? Recent versions of the Kafka client [periodically send a heartbeat](https://cwiki.apache.org/confluence/display/KAFKA/KIP-62%3A+Allow+consumer+to+send+heartbeats+from+a+background+thread) to the brokers that is decoupled from applications calling `poll()`, so that they should not get removed as long as the consumer is still open, even when they stop polling.

**Comment by thiloplanz** [comment]
>> When the queue is full, the partitions on the consumer must be paused and polling must continue (or the consumer will be removed from the consumer group)

> Is this still an issue?

It is indeed. 

The Kafka client can be configured with a `max.poll.interval.ms` that can be set quite high (without affecting the liveness check), but you still have to poll at least once in each of these intervals.

So yes, if the queue gets full, the consumer needs to be `pause()`d, and it has to continue to `poll()` while it is paused.

:-/

On the plus side, if we can get this right, it would relieve a lot of headaches and potential problems due to misconfiguration for users that are present in other Kafka libraries. #selling-point

**Comment by tuleism** [comment]
>See https://github.com/iravid/fs2-kafka-streams/blob/master/src/main/scala/com/iravid/fs2/kafka/client/RecordStream.scala#L262 for a previous implementation.

@iravid Correct me if I'm wrong: here I see `applyRebalanceEvents` is being applied after a `poll`. Only at this point, it `.complete` the processing queue for a revoked `TopicPartition`. So both message processing and offset committing can still happen shortly after this point? If this `TopicPartition` is not assigned to the consumer anymore, it will still process messages and commit offsets until the queue is fully consumed (and Kafka doesn't prevent the consumer from committing offsets for unassigned `TopicPartition`).

Shouldn't it be handled at the rebalance listener step (`onPartitionsRevoked`)? Also, with zio, the queue would stop right at that point, allow us to do a commit before the rebalance.

**Comment by iravid** [comment]
Hi @tuleism, you're right - handling the rebalance events should happen before the poll has finished, and the linked implementation is flawed in that regard. Note that it doesn't allow for a user-defined rebalance listener and therefore doesn't allow for committing before a partition is revoked. If it would, we'd have to implement it as you mention.

Another point is that the Kafka consumer would actually throw an exception when trying to commit an unassigned partition. Seen that happen a few times with the Akka Streams client.

For this implementation, we should definitely address that.
